image: node:20

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test:
  stage: test
  script:
    - npm run test -- --run
  artifacts:
    when: always
    reports:
    expire_in: 1 week
  only:
    - main
    - merge_requests

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  needs: []
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
    - npm ci
  script:
    - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"
  needs:
    - job: build
  only:
    - main